# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Ansh Goyal"
first_name: Ansh
middle_name:
last_name: Goyal
contact_note: >
  The best way to reach me is by email or LinkedIn.
description: >
  Biomedical Engineering & Computer Science at Johns Hopkins University.
  Building intelligent biomedical systems that bridge data, devices, and deep learning.
footer_text: >
  © 2025 Ansh Goyal. Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> using the 
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted on 
  <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: biomedical engineering, deep learning, intracranial pressure, stroke segmentation, portfolio
lang: en
icon: 🧬

url: "https://anshgoyal.github.io"
baseurl:
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: false
posts_in_search: false
bib_search: false
max_width: 930px

# -----------------------------------------------------------------------------
# Analytics (optional)
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

# -----------------------------------------------------------------------------
# Collections (keep only what you use)
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /projects/:name

# -----------------------------------------------------------------------------
# Markdown + Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - _news/
  - _posts/
  - _books/
  - _bibliography/
  - _pages/blog.md
  - _pages/books.md
  - _pages/publications.md
  - _pages/repositories.md
  - assets/jupyter/
  - lighthouse_results/

keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plugins (trimmed to essentials)
# -----------------------------------------------------------------------------

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Scholar (disable academic publication features)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Goyal]
  first_name: [Ansh]
  enabled: false

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_masonry: true
enable_math: false
enable_progressbar: true
enable_navbar_social: false
enable_tooltips: false
enable_project_categories: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# External links behavior
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

# -----------------------------------------------------------------------------
# Responsive WebP images (disabled for simplicity)
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false
lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional analytics flags (off)
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false

# -----------------------------------------------------------------------------
# Third-party library configuration (empty to prevent plugin error)
# -----------------------------------------------------------------------------
third_party_libraries: {}

# -----------------------------------------------------------------------------
# Theme colors and style
# -----------------------------------------------------------------------------
sass:
  style: compressed

# -----------------------------------------------------------------------------
# Author metadata
# -----------------------------------------------------------------------------

author:
  name: "Ansh Goyal"
  avatar: "/assets/img/profile.jpg"
  bio: >
    Biomedical Engineering & Computer Science student at Johns Hopkins University.
    Researching non-invasive intracranial pressure estimation and stroke lesion segmentation.

# -----------------------------------------------------------------------------
# Socials (linked via _data/socials.yml)
# -----------------------------------------------------------------------------

# Update _data/socials.yml to include:
github: anshgoyal1123
linkedin: ansh-goyal-044886217
email: agoyal19@jh.edu
