# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Ansh Goyal"
first_name: Ansh
middle_name:
last_name: Goyal
contact_note: >
  The best way to reach me is by email or LinkedIn.
description: >
  Biomedical Engineering & Computer Science at Johns Hopkins University.
  Building intelligent biomedical systems that bridge data, devices, and deep learning.
footer_text: >
  © 2025 Ansh Goyal. Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> using the 
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted on 
  <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: biomedical engineering, deep learning, intracranial pressure, stroke segmentation, portfolio
lang: en
icon: 🧬

url: "https://anshgoyal.github.io"
baseurl:
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: false
posts_in_search: false
bib_search: false
max_width: 930px

# -----------------------------------------------------------------------------
# Analytics (optional)
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

# -----------------------------------------------------------------------------
# Collections (keep only what you use)
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /projects/:name

# -----------------------------------------------------------------------------
# Markdown + Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - _news/
  - _posts/
  - _books/
  - _bibliography/
  - _pages/blog.md
  - _pages/books.md
  - _pages/publications.md
  - _pages/repositories.md
  - assets/jupyter/
  - lighthouse_results/

keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plugins (trimmed to essentials)
# -----------------------------------------------------------------------------

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Scholar (disable academic publication features)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Goyal]
  first_name: [Ansh]
  enabled: false

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_masonry: true
enable_math: false
enable_progressbar: true
enable_navbar_social: false
enable_tooltips: false
enable_project_categories: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# External links behavior
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

# -----------------------------------------------------------------------------
# Responsive WebP images (disabled for simplicity)
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false
lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional analytics flags (off)
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false

# -----------------------------------------------------------------------------
# Third-party library configuration (mirrors al-folio defaults)
# -----------------------------------------------------------------------------
third_party_libraries:
  download: false
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
    version: "1.22.4"
  chartjs:
    integrity:
      js: "sha256-0q+JdOlScWOHcunpUk21uab1jW7C1deBQARHtKMcaB4="
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@{{version}}/dist/chart.umd.min.js"
    version: "4.4.1"
  d3:
    integrity:
      js: "sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw="
    url:
      js: "https://cdn.jsdelivr.net/npm/d3@{{version}}/dist/d3.min.js"
    version: "7.8.5"
  diff2html:
    integrity:
      css: "sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg="
      js: "sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY="
    url:
      css: "https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/css/diff2html.min.css"
      js: "https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/js/diff2html-ui.min.js"
    version: "3.4.47"
  echarts:
    integrity:
      js:
        library: "sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY="
        dark_theme: "sha256-sm6Ui9w41++ZCWmIWDLC18a6ki72FQpWDiYTDxEPXwU="
    url:
      js:
        library: "https://cdn.jsdelivr.net/npm/echarts@{{version}}/dist/echarts.min.js"
        dark_theme: "https://cdn.jsdelivr.net/npm/echarts@{{version}}/theme/dark-fresh-cut.js"
    version: "5.5.0"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  highlightjs:
    integrity:
      css:
        light: "sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY="
        dark: "sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk="
    url:
      css:
        light: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github.min.css"
        dark: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github-dark.min.css"
    version: "11.9.0"
  imagesloaded:
    integrity:
      js: "sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc="
    url:
      js: "https://cdn.jsdelivr.net/npm/imagesloaded@{{version}}/imagesloaded.pkgd.min.js"
    version: "5.0.0"
  img-comparison-slider:
    integrity:
      css: "sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8="
      js: "sha256-EXHg3x1K4oIWdyohPeKX2ZS++Wxt/FRPH7Nl01nat1o="
      map: "sha256-3wfqS2WU5kGA/ePcgFzJXl5oSN1QsgZI4/edprTgX8w="
    url:
      css: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/styles.min.css"
      js: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.min.js"
      map: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.js.map"
    version: "8.0.6"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"
  leaflet:
    integrity:
      css: "sha256-q9ba7o845pMPFU+zcAll8rv+gC+fSovKsOoNQ6cynuQ="
      js: "sha256-MgH13bFTTNqsnuEoqNPBLDaqxjGH+lCpqrukmXc8Ppg="
      js_map: "sha256-YAoQ3FzREN4GmVENMir8vgHHypC0xfSK3CAxTHCqx1M="
    local:
      images: "images/"
    url:
      css: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.css"
      images: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/images/"
      js: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.js.map"
    version: "1.9.4"
  lightbox2:
    integrity:
      css: "sha256-uypRbsAiJcFInM/ndyI/JHpzNe6DtUNXaWEUWEPfMGo="
      js: "sha256-A6jI5V9s1JznkWwsBaRK8kSeXLgIqQfxfnvdDOZEURY="
    url:
      css: "https://cdn.jsdelivr.net/npm/lightbox2@{{version}}/dist/css/lightbox.min.css"
      js: "https://cdn.jsdelivr.net/npm/lightbox2@{{version}}/dist/js/lightbox.min.js"
    version: "2.11.5"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    local:
      fonts: "output/chtml/fonts/woff-v2/"
    url:
      fonts: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/output/chtml/fonts/woff-v2/"
      js: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js"
    version: "3.2.2"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      css_map: "sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
      js_map: "sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      css_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css.map"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js.map"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-2zzKJ6EMeNsSBXua0S4WneqyKxeveayq22y+Vosnvss="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js"
    version: "1.1.0"
  mermaid:
    integrity:
      js: "sha256-q3XM3Zipd51WJ1mYinhXkLzrz0ikiDC51nL5ByHMuA4="
    url:
      js: "https://cdn.jsdelivr.net/npm/mermaid@{{version}}/dist/mermaid.min.js"
    version: "10.9.0"
  photoswipe:
    integrity:
      css: "sha256-Bbu+AUgRRGmpnaF0W0nALpN+TEZEehrrheVHIX+CXAo="
      js: "sha256-h4dpbzCw8t52FGaiZF79elzloM5mN2YoQfRq8z/xJ70="
    url:
      css: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.css"
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.esm.min.js"
    version: "5.4.4"
  photoswipe-lightbox:
    integrity:
      js: "sha256-5mIoQmfTy9+W4fBbiaTbhfVbk27eU8yHZ5mQnJhCWuw="
    url:
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe-lightbox.esm.min.js"
    version: "5.4.4"
  plotly:
    integrity:
      js: "sha256-jbhjqjoG5XrwUGFTQCF+hDEQooEXCfw5jt2+jpC0uJA="
    url:
      js: "https://cdn.jsdelivr.net/npm/plotly.js-dist@{{version}}/plotly.min.js"
    version: "2.27.0"
  pseudocode:
    integrity:
      css: "sha256-Exu94YfN7mg+DtP2t2ex/ZFMgypo3QdYc8Q0nSWEuzo="
      js: "sha256-tJV5Ors9LlnxRzQ2dJBOY1SVvsEKDuUugE/mIHVMLYw="
    url:
      css: "https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.css"
      js: "https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.js"
    version: "2.3.0"
  swiper:
    integrity:
      css: "sha256-N24t49Yb5J+R7d6BB6oXu/3nlC12Fofus3v5QsixT1k="
      js: "sha256-GRTMvQhZacsGTIaDruX+AhzLwnZW2cgNYrJ1p2n322U="
    url:
      css: "https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-bundle.min.css"
      js: "https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-bundle.min.js"
    version: "11.0.5"
  spotlight:
    integrity:
      css: "sha256-gy8IRFINCtzRvTuLPgndbwexZeny5xv2nQCY8MMYjTE="
      js: "sha256-ZtGEnHI2ItKsa0jpgAeItchRIsttj15oPI+nxpaRI5E="
    url:
      css: "https://cdn.jsdelivr.net/npm/spotlight.js@{{version}}/dist/css/spotlight.min.css"
      js: "https://cdn.jsdelivr.net/npm/spotlight.js@{{version}}/dist/spotlight.bundle.min.js"
    version: "0.7.8"
  tooltips:
    integrity:
      js: "sha256-dHtyBDKYhSK+FSi1kWAcFWbFrOcSb2DPPpj0JT52v/M="
    url:
      js: "https://cdn.jsdelivr.net/npm/@popperjs/core@{{version}}/dist/umd/popper.min.js"
    version: "2.11.8"
  typograms:
    integrity:
      js: "sha256-ANS4ekKFN93exk22kEy5cmnDVlFZb1j99QydLvQRnWw="
    url:
      js: "https://cdn.jsdelivr.net/npm/typograms@{{version}}/dist/typograms.min.js"
    version: "2.4.3"
  vega:
    integrity:
      js: "sha256-wI+Anw1FgJHm1lLBbEyA62zzTBlbWzENsvNAGlku/mc="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega@{{version}}/build/vega.min.js"
    version: "5.27.0"
  vega-lite:
    integrity:
      js: "sha256-QASnwg33sXhimlcserfAA67k4hLaHUcCbUc94eoxxmI="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-lite@{{version}}/build/vega-lite.min.js"
    version: "5.17.0"
  vega-embed:
    integrity:
      js: "sha256-bdDd3DdHD2GH+j1D53pLhz92boyhbVo7+qoxMM50SbQ="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-embed@{{version}}/build/vega-embed.min.js"
    version: "6.24.0"
  venobox:
    integrity:
      css: "sha256-0wJ36StXQguMBG0ts2h5qhVTdneJKBAsuTBXzN1VG7k="
      js: "sha256-Pm1iRD4gKqtTQVd8T0oNsn7VtQgR6A3sSxXb/6pwRot="
    url:
      css: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.css"
      js: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.js"
    version: "2.1.8"

# -----------------------------------------------------------------------------
# Theme colors and style
# -----------------------------------------------------------------------------
sass:
  style: compressed

# -----------------------------------------------------------------------------
# Author metadata
# -----------------------------------------------------------------------------

author:
  name: "Ansh Goyal"
  avatar: "/assets/img/profile.jpg"
  bio: >
    Biomedical Engineering & Computer Science student at Johns Hopkins University.
    Researching non-invasive intracranial pressure estimation and stroke lesion segmentation.

# -----------------------------------------------------------------------------
# Socials (linked via _data/socials.yml)
# -----------------------------------------------------------------------------

# Update _data/socials.yml to include:
github: anshgoyal1123
linkedin: ansh-goyal-044886217
email: agoyal19@jh.edu
